[project]
name = 'stacks-arena'
description = 'Bitcoin-native commitment protocol. Lock Bitcoin under programmable rules on Stacks L2.'
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []

[contracts.ConditionEngine]
path = 'contracts/ConditionEngine.clar'
clarity_version = 2
epoch = '2.5'

[contracts.CommitVault]
path = 'contracts/CommitVault.clar'
clarity_version = 2
epoch = '2.5'

[contracts.VaultFactory]
path = 'contracts/VaultFactory.clar'
clarity_version = 2
epoch = '2.5'

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
