[project]
name = 'stacks-arena'
description = 'Bitcoin-native commitment protocol. Lock Bitcoin under programmable rules on Stacks L2.'
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []

[contracts.stacksarena-ConditionEngine-fix]
path = 'contracts/ConditionEngine.clar'
clarity_version = 2
epoch = '2.5'

[contracts.stacksarena-CommitVaults-v2]
path = 'contracts/CommitVault.clar'
clarity_version = 2
epoch = '2.5'

[contracts.stacksarena-VaultFactory-fix]
path = 'contracts/VaultFactory.clar'
clarity_version = 2
epoch = '2.5'

[contracts.stacksarena-sip-010-trait-fix]
path = 'contracts/sip-010-trait-ft-standard.clar'
clarity_version = 2
epoch = '2.5'

[contracts.vault-factory-trait]
path = 'contracts/vault-factory-trait.clar'
clarity_version = 2
epoch = '2.5'

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
